### ISSUE TITLE
Android Soon?

### ISSUE THREAD

**Issue by kuraydev** [kyle-ssg/react-native-simple-svg#3]
Hi @kyle-ssg,
I love the performant and external SVG idea on ReactNative. Do you have a plan to integrate Android soon?

**Comment by kyle-ssg** [comment]
Hey @WrathChaos, I only had a very temporary usecase for this so I'm not actively working on it. However to answer your question I'm not so sure that Android has native SVG that I could piggyback off of.

I'd consider maybe trying out a webview wrapper, I do wonder whether that's faster than react-native-svg.

**Comment by kyle-ssg** [comment]
A quick google search shows that this lib in fact did exactly that https://github.com/seekshiva/react-native-remote-svg/blob/master/SvgImage.js

**Comment by kuraydev** [comment]
@kyle-ssg unfortunately, it has some problems on iOS part, I'm looking for full coverage of iOS and Android. I hope one day huh :)
Thank you.
